### ISSUE TITLE
auto-expand

### ISSUE THREAD

**Issue by serapath** [monsterkodi/tree-view-filter#4]
Hey there :-)
I have a convention, where next to `@TODO` comments in my files, i sometimes create `@todo.md` and `@TODO/` folders to store more complex information about what needs to be done.

The `ctrl-shift-f` search does not find those files and folders if they do not contain `@TODO` comments.
I was hoping the `tree-view-filter` will be able to quickly show me all my `@TODO/` and `@todo.md` files/folders, and it does if they are currently visible in the tree-view already, but it does not **open** or **auto-expand** the tree view to show me those.
Next is, that in general folders are still shown, so i cannot visually distinguish between normal folders and `@TODO/` folders, so a color highlight would be great too :-)

Otherwise, if you have any suggestions of how to solve my problem of quickly getting an overview over all my `@TODO/` folders and `@todo.md` files, that would be highly appreciated :-)

otherwise, :+1:

**Comment by monsterkodi** [comment]
Hello serapath,

the tree-view-filter was made to hide uninteresting files, 
you want to find and highlight files, which is a slightly different use case.

And since the tree-view package is lacking a plugin API I don't plan to add features to the filter. 

To solve your problem, I would try the following:
Clone https://github.com/postcasio/tree-view-open-files and change it to display your TODO files.
You could use the https://www.npmjs.com/package/walkdir package to find the files below the root directories in the tree.

Have fun, yours monsterkodi

**Comment by serapath** [comment]
thank you, i will investigate the links :-)
